### ISSUE TITLE
Do no want to show pending results in a result table.

### ISSUE THREAD

**Issue by khushal-Gupta-94** [alapanme/Cypress-Automation#1]
Hi,

Thanks for making repository. As it helped me a lot. However, I am facing an issue that I don't want to show pending test result on the result table(For not executed test cases). Please suggest me how to handle this situation.

Thanks,
Khushal Gupta

**Comment by alapanme** [comment]
Hey Kushal,

The report table that you see comes from Mocha, since cypress is built on top of Mocha JS. You can learn more about it from here - https://github.com/cypress-io/testing-workshop-cypress/blob/master/slides/09-reporters/PITCHME.md. Since Mocha is an Open sourced library I believe that what you are looking for is achievable but it would require you to dig deeper into Mocha reporting structure. Unfortunately there isn't an easy way to do it.
